import { chromium } from '@playwright/test';
import assert from 'node:assert/strict';
const base = process.env.TEST_BASE_URL || 'http://127.0.0.1:3000';
const browser = await chromium.launch({channel:'chrome',headless:true});
const context = await browser.newContext({viewport:{width:1440,height:1080}});
const page = await context.newPage();
const errors=[]; page.on('pageerror',e=>errors.push(e.message));
const links=[]; const venues=[];
const headers={Origin:base};
const design={foreground:'#173E36',background:'#FFFFFF',dots:'square',corners:'square',logo:null};
try {
 await page.goto(base);
 await page.getByRole('button',{name:/Mis locales/}).click();
 await page.getByLabel('Nombre del nuevo local').fill('Local de prueba Centro');
 let response=page.waitForResponse(r=>r.url().endsWith('/api/venues')&&r.request().method()==='POST');
 await page.getByRole('button',{name:'Crear local',exact:true}).click();
 const created=await response; assert.equal(created.status(),201);
 const venue=(await created.json()).venue; venues.push(venue);
 let row=page.locator('.venue-row').filter({hasText:'Local de prueba Centro'});
 await row.getByRole('button',{name:'Agregar menú'}).click();
 assert.equal(await page.getByLabel('Local',{exact:true}).inputValue(),venue.id);
 assert.equal(await page.getByLabel('Uso del enlace').inputValue(),'menu');
 await page.getByLabel('Nombre del QR').fill('Menú de prueba Centro');
 await page.getByLabel('Enlace de destino',{exact:true}).fill('https://example.com/menu-externo');
 response=page.waitForResponse(r=>r.url().endsWith('/api/qrs')&&r.request().method()==='POST');
 await page.getByRole('button',{name:'Crear mi QR',exact:true}).click();
 const menu=(await (await response).json()).record; links.push(menu);
 assert.equal(menu.venue_id,venue.id); assert.equal(menu.kind,'menu');
 const permanent=`${base}/r/${menu.slug}`;
 assert.equal((await context.request.get(permanent,{maxRedirects:0})).headers().location,'https://example.com/menu-externo');
 assert.equal((await context.request.post(`${base}/api/qrs`,{headers,data:{...menu,name:'Duplicate'}})).status(),409);
 assert.equal((await context.request.delete(`${base}/api/venues/${venue.id}`,{headers})).status(),409);
 assert.equal((await context.request.post(`${base}/api/qrs`,{headers,data:{name:'Loop',destination:permanent,active:true,design}})).status(),400);
 assert.equal((await context.request.post(`${base}/api/qrs`,{headers,data:{name:'No venue',destination:'https://example.com',active:true,design,kind:'menu'}})).status(),400);
 await page.getByRole('button',{name:/Mis locales/}).click();
 row=page.locator('.venue-row').filter({hasText:'Local de prueba Centro'});
 await row.getByRole('button',{name:'Renombrar'}).click();
 await page.getByLabel('Editar nombre del local').fill('Centro actualizado');
 response=page.waitForResponse(r=>r.url().endsWith(`/api/venues/${venue.id}`)&&r.request().method()==='PATCH');
 await page.getByRole('button',{name:'Guardar local'}).click();
 assert.equal((await response).status(),200);
 await page.locator('.venue-row').filter({hasText:'Centro actualizado'}).waitFor();
 await page.screenshot({path:'.impeccable/screenshots/venues-desktop.png',fullPage:true});
 await page.setViewportSize({width:390,height:844});
 await page.screenshot({path:'.impeccable/screenshots/venues-mobile.png',fullPage:true});
 assert.ok(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth));
 await page.setViewportSize({width:1440,height:1080});
 await page.getByRole('button',{name:'Acortar una URL',exact:true}).click();
 await page.getByLabel('Nombre del QR').fill('Promoción NFC');
 await page.getByLabel('Local',{exact:true}).selectOption(venue.id);
 await page.getByLabel('Enlace de destino',{exact:true}).fill('https://example.com/promocion/larga?campaign=mesa1');
 response=page.waitForResponse(r=>r.url().endsWith('/api/qrs')&&r.request().method()==='POST');
 await page.getByRole('button',{name:'Acortar URL',exact:true}).click();
 const short=(await (await response).json()).record; links.push(short); assert.equal(short.kind,'short');
 await page.getByText('Safari no permite grabar NFC.',{exact:false}).waitFor();
 await page.screenshot({path:'.impeccable/screenshots/short-desktop.png',fullPage:true});
 await page.setViewportSize({width:390,height:844});
 await page.screenshot({path:'.impeccable/screenshots/short-mobile.png',fullPage:true});
 assert.ok(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth));
 await page.setViewportSize({width:1440,height:1080});
 await page.getByRole('button',{name:/Mis códigos QR/}).click();
 await page.getByLabel('Filtrar por local').selectOption(venue.id);
 await page.getByLabel('Filtrar por uso').selectOption('short');
 await page.getByRole('button',{name:'Promoción NFC',exact:true}).waitFor();
 assert.equal(await page.getByRole('button',{name:'Menú de prueba Centro',exact:true}).count(),0);
 await page.getByRole('button',{name:'Pausar Promoción NFC',exact:true}).click();
 await page.getByRole('button',{name:'Reactivar Promoción NFC',exact:true}).waitFor();
 assert.equal((await context.request.get(`${base}/r/${short.slug}`,{maxRedirects:0})).status(),404);
 await page.reload();
 await page.getByRole('button',{name:/Mis locales/}).click();
 await page.locator('.venue-row').filter({hasText:'Centro actualizado'}).getByRole('button',{name:'Editar menú'}).click();
 assert.equal(await page.getByLabel('Enlace permanente del QR').inputValue(),permanent);
 assert.deepEqual(errors,[]);
 console.log('PASS: create/rename venues, menu assignment and uniqueness, external redirect, stable URL, short links, filters, pause, persistence, loop rejection, protected deletion, desktop/mobile.');
} finally {
 for(const link of links) await context.request.delete(`${base}/api/qrs/${link.id}`,{headers});
 for(const venue of venues) await context.request.delete(`${base}/api/venues/${venue.id}`,{headers});
 await browser.close();
}
